# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
    paths-ignore:
      - 'assets/**'
      - 'profile-3d-contrib/**'
      - 'profile-summary-card-output/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake.gif

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets'
          message: 'chore: regenerate contribution snake'
