name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:
  schedule:
    # daily at 18:00 UTC
    - cron: "0 18 * * *"
  push:
    branches: [main]
    paths-ignore:
      - 'profile-3d-contrib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A profile-3d-contrib
          git commit -m "chore: regenerate 3D contribution calendar" || echo "no changes"
          git push
