name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:
  schedule:
    # daily at 18:00 UTC
    - cron: "0 18 * * *"
  push:
    branches: [main]
    paths-ignore:
      - 'profile-summary-card-output/**'
      - 'profile-3d-contrib/**'
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: 'main'
          THEME: 'github_dark'
